name: "Install depentdencies"
runs:
  using: composite
  steps:
    - name: Print step name
      run: echo "Installing all required dependecies.."
      shell: cmd
    - name: Install all depentdencies
      run: py -m pip install -r requirements.txt
      working-directory: python-greetings
      shell: pwsh